debug step need

diff --git a/.github/workflows/debug.yaml b/.github/workflows/debug.yaml
--- a/.github/workflows/debug.yaml
+++ b/.github/workflows/debug.yaml
@@ -40,10 +40,6 @@ jobs:
          #new_k: "${{env.NEW_PREFIX}}"
       run: |
         echo "show action info"
-        echo "github action is $GITHUB_ACTION"
-        echo "GITHUB ACTOR is $GITHUB_ACTOR"
-        echo "GITHUB_ACTOR_ID is $GITHUB_ACTOR_ID"
-        echo "GITHUB_RUN_ID is $GITHUB_RUN_ID"
         echo "runid and jobname is: ${GITHUB_RUN_ID}-${GITHUB_JOB}"
         source activate internlm-env-test
         echo "show env info"
@@ -80,20 +76,19 @@ jobs:
       run: |
         #echo ${{ secrets.NEW_PREFIX }}        
         echo "show action info in child job"
-        echo "parititon is ${PARTITON}"
-        echo "github action is $GITHUB_ACTION"
-        echo "GITHUB ACTOR is $GITHUB_ACTOR"
-        echo "GITHUB_ACTOR_ID is $GITHUB_ACTOR_ID"
-        echo "GITHUB_RUN_ID is $GITHUB_RUN_ID"
-        tmpvar=$GITHUB_RUN_ID-$GITHUB_JOB
-        echo $tmpvar
         echo "runid and jobname is: $GITHUB_RUN_ID-$GITHUB_JOB"
         echo "again..${{env.new_k}}"
         #srun -p llm2 --job-name=${GITHUB_RUN_ID}-${GITHUB_JOB} sleep 150
         source activate internlm-env-test
         #sh ci_scripts/data/tmp.sh "$GITHUB_RUN_ID-$GITHUB_JOB"
-        sh ci_scripts/data/tmp.sh
-    
+        #sh ci_scripts/data/tmp.sh
+    - name: chatonetest
+      id: chatidone 
+      run: exit 1
+    - name: debug step need
+      if: ${{ failure() && steps.chatidone.conclusion == 'failure' }}
+      run: |
+        echo "the step chatonetest has failed!"
     - name: chattwo
       run: |
         echo "runid and jobname is: $GITHUB_RUN_ID'_'$GITHUB_JOB"
